from app.services.auth_service import hash_password, verify_password


def test_password_hash_round_trip_and_wrong_password_rejection():
    encoded = hash_password('Correct Horse Battery Staple!')
    assert encoded.startswith('$pbkdf2-sha256$600000$')
    assert verify_password('Correct Horse Battery Staple!', encoded) is True
    assert verify_password('wrong password', encoded) is False


def test_existing_passlib_pbkdf2_sha256_hashes_remain_compatible():
    # Generated by passlib 1.7.4 before the dependency was removed.
    encoded = '$pbkdf2-sha256$29000$sdZaq5WylpJyTmnNmVMqBQ$L6vc9cHJ2O62KcXniBa/dxGHTR6dP3LAAx3c.YbuqMM'
    assert verify_password('test', encoded) is True
    assert verify_password('not-test', encoded) is False


def test_malformed_password_hashes_fail_closed():
    for encoded in ('', 'plain-text', '$pbkdf2-sha256$bad$salt$digest', '$other$1$salt$digest'):
        assert verify_password('anything', encoded) is False
